name: First Workflow
on: 
  push:
    # only trigger on branches, not on tags
    branches: 'main'


jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - tchau!"